[env]
ANDROID_HOME = "{{env.HOME}}/.local/share/mise/installs/android-sdk/21.0"
_.path = [
  "{{env.HOME}}/.local/share/mise/installs/android-sdk/21.0/cmdline-tools/21.0/bin",
  "{{env.HOME}}/.local/share/mise/installs/android-sdk/21.0/platform-tools",
  "{{env.HOME}}/.local/share/mise/installs/android-sdk/21.0/emulator",
]

[tools]
java = "21"
